field.storage_settings.daterange_timezone:
  type: field.storage_settings.daterange
  label: 'Datetime Range Timezone field'

field.formatter.settings.daterange_timezone:
  type: mapping
  label: 'Date range and timezone formatter'
  mapping:
    separator:
      type: label
      label: 'Separator'
    format_type:
      type: string
      label: 'The date format'
    display_timezone:
      type: boolean
      label: 'Show or hide the timezone'
